### Login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123"
}

### get user by token
GET http://localhost:8080/api/auth/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoxMSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTcyODUzNjg1MiwiZXhwIjoxNzI4NjIzMjUyfQ.FVhNA0WTVbLWaX3_uw28sN5WGQS4e2Ps27XRXzlgMlI

### Login with token
POST http://localhost:8080/api/auth/login HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoxMSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTcyODUzNjg1MiwiZXhwIjoxNzI4NjIzMjUyfQ.FVhNA0WTVbLWaX3_uw28sN5WGQS4e2Ps27XRXzlgMlI

### Register
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "customer1@gmail.com",
    "password": "123",
    "username": "haha",
    "phoneNumber": "0123456789"
}

### get book by id
GET http://localhost:8080/api/book/1 HTTP/1.1

### Update book
POST http://localhost:8080/api/book/1 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoxMSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTcyOTA4Njg2NywiZXhwIjoxNzI5MTczMjY3fQ.JqO5fko7PHToozpb1VQJ4zNcYdXbhx5grbhjksm-b74
Content-Type: application/json

{
  "discount_id": 2
}

### Get book page
GET http://localhost:8080/api/book?page=2&limit=1&type=all&q= HTTP/1.1

### lay tat ca gia tri trong combo box form them sach
GET http://localhost:8080/api/book/reference/all HTTP/1.1


